// tools/lint-layer0.mjs — the Layer-0 lint hook (node G4, owner I4).
// Zero model calls. Scans for banned legacy WebMCP identifiers, the 500-char
// tool-description budget, banned wording (erp/RISK.md §2) and retracted
// claims (erp/FACTS.md §9/§9a), and is the second clause of L1's merge gate
// for every node merged after this one this week.
//
//   node tools/lint-layer0.mjs                 scan the whole repo
//   node tools/lint-layer0.mjs <file> [file...] scan only the given files
//   node tools/lint-layer0.mjs --selftest       internal self-checks
//   node tools/lint-layer0.mjs --assert-register
//       prove kb/webmcp/RETRACTED.txt carries the five required strings
//   node tools/lint-layer0.mjs --check-restrictions
//       D-43: for every ruled phrase restriction in RULED_RESTRICTIONS below,
//       prove either its registry row exists (kb/webmcp/BANNED.txt /
//       RETRACTED.txt) or its exemption is recorded in erp/DECISIONS.md.
//       This does NOT discover new restrictions from prose — that stays a
//       manual sweep (D-41) — it only proves the known ones haven't drifted
//       silently out of coverage.

import fs from "node:fs";
import path from "node:path";
import { execFileSync } from "node:child_process";

const REPO_ROOT = process.cwd();
const BANNED_FILE = "kb/webmcp/BANNED.txt";
const RETRACTED_FILE = "kb/webmcp/RETRACTED.txt";
const DESC_BUDGET = 500;

// The exclusion list is a LITERAL ARRAY IN THE SOURCE, never satisfied by
// deleting quotes from the files that quote banned strings in order to ban
// them (erp/RISK.md §2 / erp/graph.json G4.accept, verbatim):
//   erp/**, kb/webmcp/BANNED.txt, kb/method/BANNED-CITATIONS.md,
//   .team/lint/banned.txt
const EXCLUDE = ["erp/**", "kb/webmcp/BANNED.txt", "kb/method/BANNED-CITATIONS.md", ".team/lint/banned.txt"];

// kb/webmcp/RETRACTED.txt is NOT on that array (checked three times against
// erp/RISK.md, erp/graph.json and this node's charter — it is omitted on
// purpose in all three, not an oversight). It is still, structurally, the
// same kind of file as kb/webmcp/BANNED.txt: a registry that must quote the
// five retracted strings in order to register them for --assert-register.
// Scanning it with the WORD/RC patterns sourced from those same five strings
// would make the registry fail the lint by construction, so it is skipped by
// a SEPARATE mechanism from EXCLUDE, named separately so EXCLUDE itself stays
// exactly the four-entry array the accept predicate names. Nothing here
// weakens a ban: no pattern is removed and no quote is deleted anywhere else.
const REGISTER_FILES = [RETRACTED_FILE];

// SWEEP_EXCLUDE is a THIRD, separate mechanism — not the accept predicate's
// four-entry EXCLUDE array, not REGISTER_FILES. It excludes one class of
// file, named as a principle so the next entry has to argue against a stated
// rule rather than pattern-match a growing list:
//
//   (i)  a verbatim extract of an already-excluded file. Its content is
//        generated byte-for-byte from a file already on EXCLUDE, so scanning
//        it is scanning that excluded file wearing a different path.
//        `.team/contracts/**` is this: every ACCEPT field is lifted verbatim
//        from erp/graph.json by tools/contract.mjs, and erp/** is already
//        on EXCLUDE.
//
// A pit (kb/pits/**) is NOT this class and is deliberately not excluded: a
// pit is authored, not generated, and nothing else in the project reads it —
// no test, no schema, no review step. A blanket exclusion there would buy a
// false-positive class at the price of the only instrument that would ever
// check a retracted claim planted in the one file class with no other
// reader. The rule a pit follows instead: it names the ruling and states the
// correct claim, it does not quote the retracted string verbatim — see
// kb/pits/G4.md for a worked example. (`--selftest` proves this class is
// actually caught: see the planted-pit-assertion check below.)
//
// Two named files fit neither class but still can't trip the default sweep:
//   - tools/lint-layer0.mjs: this file's own source, whose doc comments and
//     BW-14 selftest fixtures literally contain the phrases they exist to ban.
//   - tests/fixtures/banned-sample.js: the committed fixture, planted with
//     one of every banned class so clause 2 can name it explicitly and watch
//     it fail — it must not also break clause 1's argument-less sweep merely
//     by sitting in the tree.
//
// Clause 1 of the accept predicate (`node tools/lint-layer0.mjs` exits 0) is
// a repo-wide SWEEP with no path named on the command line; clause 2 (the
// fixture run) always names a path explicitly. SWEEP_EXCLUDE applies ONLY to
// the argument-less default sweep in main() — a file matching a class above,
// or named below, is still scanned, and still fails, the moment it is named
// explicitly. That is the only reading under which both clauses hold at
// once: the sweep must not walk files that exist to carry the strings it
// bans, while an explicit path is always honoured. The predicate's own
// four-entry EXCLUDE array above is untouched by any of this.
const SWEEP_EXCLUDE = ["tools/lint-layer0.mjs", "tests/fixtures/banned-sample.js", ".team/contracts/**"];

function isSweepExcluded(relPath) {
  for (const entry of SWEEP_EXCLUDE) {
    if (entry.endsWith("/**")) {
      const prefix = entry.slice(0, -2); // "kb/pits/**" -> "kb/pits/"
      if (relPath.startsWith(prefix)) return true;
    } else if (relPath === entry) {
      return true;
    }
  }
  return false;
}

function isExcluded(relPath) {
  for (const entry of EXCLUDE) {
    if (entry.endsWith("/**")) {
      const prefix = entry.slice(0, -2); // "erp/**" -> "erp/"
      if (relPath.startsWith(prefix)) return true;
    } else if (relPath === entry) {
      return true;
    }
  }
  return false;
}

function isRegisterFile(relPath) {
  return REGISTER_FILES.includes(relPath);
}

function inIdentScope(relPath) {
  return relPath.startsWith("src/") || relPath.startsWith("tests/");
}

// ── pattern registry ────────────────────────────────────────────────────

function loadPatterns(bannedFilePath = BANNED_FILE) {
  const abs = path.join(REPO_ROOT, bannedFilePath);
  const text = fs.readFileSync(abs, "utf8");
  const patterns = { IDENT: [], WORD: [], RC: [] };
  for (const rawLine of text.split("\n")) {
    const line = rawLine.replace(/\r$/, "");
    if (!line.trim() || line.trim().startsWith("#")) continue;
    const parts = line.split("\t");
    if (parts.length < 3) continue;
    const [cls, id, ...rest] = parts;
    const pattern = rest.join("\t");
    if (!patterns[cls]) continue;
    patterns[cls].push({ id, pattern });
  }
  return patterns;
}

function escapeRegex(s) {
  return s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

// erp/RISK.md §2 rule 5: a pattern that begins with a word character is
// anchored with \b — a bare pattern is a substring match, and an English
// phrase is very often a substring of an innocent longer word.
function wordRegex(pattern) {
  const escaped = escapeRegex(pattern);
  const anchored = /^\w/.test(pattern) ? `\\b${escaped}` : escaped;
  return new RegExp(anchored, "i");
}

// erp/RISK.md §2 rule 4: patterns assume a whitespace-normalised stream, so
// a single literal space matches any run of whitespace including a line
// break.
function normalizeWhitespace(text) {
  return text.replace(/\s+/g, " ");
}

// ── file listing ────────────────────────────────────────────────────────

function gitLsFiles() {
  const out = execFileSync("git", ["ls-files"], { cwd: REPO_ROOT, encoding: "utf8" });
  return out.split("\n").filter(Boolean);
}

function readFileSafe(relPath) {
  try {
    return fs.readFileSync(path.join(REPO_ROOT, relPath), "utf8");
  } catch {
    return null; // binary or unreadable; nothing this scanner checks applies
  }
}

// ── scanning ────────────────────────────────────────────────────────────

function lineOf(content, index) {
  return content.slice(0, index).split("\n").length;
}

function scanFile(relPath, patterns) {
  const violations = [];
  const content = readFileSafe(relPath);
  if (content == null) return violations;

  if (inIdentScope(relPath)) {
    for (const { id, pattern } of patterns.IDENT) {
      const idx = content.indexOf(pattern);
      if (idx !== -1) {
        violations.push({ class: "BANNED IDENTIFIER", id, pattern, file: relPath, line: lineOf(content, idx) });
      }
    }

    // 500-char description budget — not expressible as a literal, so it is
    // enforced directly rather than sourced from kb/webmcp/BANNED.txt.
    const descRe = /description:\s*(["'`])((?:\\.|(?!\1)[\s\S])*?)\1/g;
    let m;
    while ((m = descRe.exec(content))) {
      if (m[2].length > DESC_BUDGET) {
        violations.push({
          class: "DESCRIPTION BUDGET",
          id: "DESC-1",
          pattern: `${m[2].length} chars > ${DESC_BUDGET}`,
          file: relPath,
          line: lineOf(content, m.index),
        });
      }
    }
  }

  if (!isRegisterFile(relPath)) {
    const normalized = normalizeWhitespace(content);
    for (const { id, pattern } of patterns.WORD) {
      if (wordRegex(pattern).test(normalized)) {
        violations.push({ class: "BANNED WORDING", id, pattern, file: relPath });
      }
    }
    for (const { id, pattern } of patterns.RC) {
      if (wordRegex(pattern).test(normalized)) {
        violations.push({ class: "RETRACTED CLAIM", id, pattern, file: relPath });
      }
    }
  }

  return violations;
}

function report(violations) {
  const byFile = new Map();
  for (const v of violations) {
    if (!byFile.has(v.file)) byFile.set(v.file, []);
    byFile.get(v.file).push(v);
  }
  for (const [file, vs] of byFile) {
    const byClass = new Map();
    for (const v of vs) {
      if (!byClass.has(v.class)) byClass.set(v.class, []);
      byClass.get(v.class).push(v);
    }
    for (const [cls, entries] of byClass) {
      console.log(`${cls} ${file}`);
      for (const e of entries) {
        const loc = e.line ? `:${e.line}` : "";
        console.log(`  ${e.id}  ${e.pattern}${loc}`);
      }
    }
  }
}

function runScan(files) {
  const patterns = loadPatterns();
  const violations = [];
  for (const f of files) {
    if (isExcluded(f)) continue;
    violations.push(...scanFile(f, patterns));
  }
  return violations;
}

// ── --assert-register ──────────────────────────────────────────────────

const REQUIRED_RETRACTED_STRINGS = [
  "structural guarantee",
  "the five write tools",
  "a specific agent",
  "a commit cannot be made without a human decision",
  "the tool surface is the boundary",
  "--headless=new enables WebMCP with no flag",
];

function assertRegister() {
  const abs = path.join(REPO_ROOT, RETRACTED_FILE);
  if (!fs.existsSync(abs)) {
    console.log(`FAIL ${RETRACTED_FILE} does not exist`);
    return false;
  }
  const text = fs.readFileSync(abs, "utf8");
  let ok = true;
  for (const s of REQUIRED_RETRACTED_STRINGS) {
    const present = text.includes(s);
    console.log(`${present ? "OK  " : "MISS"} '${s}'`);
    if (!present) ok = false;
  }
  return ok;
}

// ── --selftest ──────────────────────────────────────────────────────────

function selftest() {
  const checks = [];
  const record = (name, pass) => checks.push({ name, pass });

  // 1. Exclusion array works: a file on EXCLUDE that legitimately quotes a
  //    banned/retracted string is not itself flagged.
  {
    const excludedTargets = [BANNED_FILE, ".team/lint/banned.txt"].filter((f) => fs.existsSync(path.join(REPO_ROOT, f)));
    let sawAny = false;
    let clean = true;
    for (const f of excludedTargets) {
      sawAny = true;
      if (!isExcluded(f)) clean = false;
    }
    // runScan() is the real gate: isExcluded() is checked before scanFile()
    // is ever called, so these files never reach the scanner at all.
    const scanned = runScan(excludedTargets);
    record("EXCLUDE array covers kb/webmcp/BANNED.txt and .team/lint/banned.txt", sawAny && clean && scanned.length === 0);
  }

  // 2. erp/** is excluded even though erp/RISK.md quotes every BW pattern
  //    and every retracted string.
  record("EXCLUDE array covers erp/**", isExcluded("erp/RISK.md") && isExcluded("erp/FACTS.md"));

  // 3. kb/webmcp/RETRACTED.txt is skipped by the WORD/RC scan (register
  //    file), but is NOT on the EXCLUDE array itself.
  record("kb/webmcp/RETRACTED.txt is a register file, not an EXCLUDE entry", isRegisterFile(RETRACTED_FILE) && !isExcluded(RETRACTED_FILE));

  // 4. BW-14 word-boundary rule, the exact test case from erp/RISK.md §2.
  {
    const re = wordRegex("our differentiator");
    const mustPass = [
      "three of our four differentiators are invisible server-side invariants",
      "four differentiators, all of them",
    ];
    const mustFire = [
      "our differentiator is the human-sign gate",
      "Our differentiator here",
      "this is our differentiators list",
    ];
    const passOk = mustPass.every((s) => !re.test(s));
    const fireOk = mustFire.every((s) => re.test(s));
    record("BW-14 \\b anchoring: innocent plural passes, real claim fires", passOk && fireOk);
  }

  // 5. Whitespace normalisation: a phrase split across a line break is still
  //    caught.
  {
    const split = "we spend cache efficiency to buy a structural\nguarantee about the workflow";
    record("whitespace-normalised match spans a line break", wordRegex("structural guarantee").test(normalizeWhitespace(split)));
  }

  // 6. Identifier scope: navigator.modelContext in probe/ (a legitimate
  //    feature-detect, not src/** or tests/**) is not in IDENT scope.
  record("IDENT scope excludes prose/feature-detect files outside src/** and tests/**", !inIdentScope("probe/index.html") && inIdentScope("src/tools.js") && inIdentScope("tests/fixtures/banned-sample.js"));

  // 7. --assert-register itself passes against the real registry.
  record("--assert-register passes against kb/webmcp/RETRACTED.txt as shipped", assertRegisterQuiet());

  // 8. The fixture, scanned for real, names every planted class.
  {
    const patterns = loadPatterns();
    const vs = scanFile("tests/fixtures/banned-sample.js", patterns);
    const classes = new Set(vs.map((v) => v.class));
    const wantClasses = ["BANNED IDENTIFIER", "DESCRIPTION BUDGET", "BANNED WORDING", "RETRACTED CLAIM"];
    const gotAll = wantClasses.every((c) => classes.has(c));
    const identIds = new Set(vs.filter((v) => v.class === "BANNED IDENTIFIER").map((v) => v.id));
    const wantIdent = ["IR-1", "IR-2a", "IR-2b", "IR-2c", "IR-4", "IR-5"];
    const gotAllIdent = wantIdent.every((i) => identIds.has(i));
    record("fixture trips every class with all six identifiers named", gotAll && gotAllIdent);
  }

  // 9. kb/pits/** is NOT sweep-excluded: a retracted claim ASSERTED inside a
  //    pit-path file must still be caught, both by the default sweep and by
  //    scanFile() directly. This is the regression test for the hole found
  //    when kb/pits/** was briefly on SWEEP_EXCLUDE — a planted assertion of
  //    "We hereby assert the five write tools" inside a pit produced zero
  //    hits under that exclusion.
  {
    const fixturePath = "kb/pits/__selftest-fixture.md";
    const abs = path.join(REPO_ROOT, fixturePath);
    fs.writeFileSync(abs, "We hereby assert the five write tools remain in force.\n");
    let vs;
    try {
      const patterns = loadPatterns();
      const notSweepExcluded = !isSweepExcluded(fixturePath);
      vs = scanFile(fixturePath, patterns);
      const caught = vs.some((v) => v.class === "RETRACTED CLAIM" && v.id === "RC-2");
      record("kb/pits/** assertion of a retracted claim is caught, not sweep-excluded", notSweepExcluded && caught);
    } finally {
      fs.unlinkSync(abs);
    }
  }

  // 10. BW-33a..e (D-44, re-anchored verb-led family, erp/graph.json V2
  //     restriction / erp/FACTS.md §9 V2 row): the honest phrasing is "on
  //     its next turn"; a document asserting the surface changes/updates/
  //     appears/refreshes/arrives "on the spot" must fail — but the three
  //     REAL prohibition sentences that forbid the phrase (which a bare
  //     fragment would have false-positived on 3/3, per D-44) must still
  //     pass, because no prohibition pairs the verb with the fragment.
  {
    const family = [
      ["BW-33a", "changes on the spot", "The surface changes on the spot."],
      ["BW-33b", "updates on the spot", "The tool list updates on the spot."],
      ["BW-33c", "appears on the spot", "The sixth tool appears on the spot."],
      ["BW-33d", "refreshes on the spot", "The surface refreshes on the spot."],
      ["BW-33e", "arrives on the spot", "The new tool arrives on the spot."],
    ];
    const patterns = loadPatterns();
    const hasAllRows = family.every(([id, pattern]) => patterns.WORD.some((p) => p.id === id && p.pattern === pattern));
    let allFire = true;
    const fixturePath = "kb/pits/__selftest-fixture-bw33.md";
    const abs = path.join(REPO_ROOT, fixturePath);
    try {
      for (const [id, , assertion] of family) {
        fs.writeFileSync(abs, assertion + "\n");
        const vs = scanFile(fixturePath, patterns);
        if (!vs.some((v) => v.class === "BANNED WORDING" && v.id === id)) allFire = false;
      }
      // the three real prohibition sentences BW-33's own history was
      // false-positiving on (docs/VIDEO-SCRIPT.md:217, evidence/V2.json:11,
      // evidence/UNKNOWNS.md:34 pre-D-42 rework) must all pass clean.
      const prohibitions = [
        'Do not say "on the spot." The surface reaches the agent on its next turn.',
        "the plan's hedge - re-prompt after the flip, never say 'on the spot' - is satisfied and can stay as written.",
        'Narration stays "on its next turn"; "on the spot" remains forbidden.',
      ];
      let noneFire = true;
      for (const sentence of prohibitions) {
        fs.writeFileSync(abs, sentence + "\n");
        const vs = scanFile(fixturePath, patterns);
        if (family.some(([id]) => vs.some((v) => v.id === id))) noneFire = false;
      }
      record("BW-33a..e catch the assertion (5/5) and clear all 3 real prohibition sentences (0/3)", hasAllRows && allFire && noneFire);
    } finally {
      if (fs.existsSync(abs)) fs.unlinkSync(abs);
    }
  }

  // 10b. RC-6 (D-45, "--headless=new enables WebMCP with no flag", IR-16(b),
  //      R-30): a document reasserting the retracted claim must fail.
  {
    const fixturePath = "kb/pits/__selftest-fixture-rc6.md";
    const abs = path.join(REPO_ROOT, fixturePath);
    fs.writeFileSync(abs, "Recall that --headless=new enables WebMCP with no flag, so no launch flag is required headless.\n");
    let vs;
    try {
      const patterns = loadPatterns();
      const hasRow = patterns.RC.some((p) => p.id === "RC-6" && p.pattern === "--headless=new enables WebMCP with no flag");
      const inRegister = REQUIRED_RETRACTED_STRINGS.includes("--headless=new enables WebMCP with no flag") && assertRegisterQuiet();
      vs = scanFile(fixturePath, patterns);
      const caught = vs.some((v) => v.class === "RETRACTED CLAIM" && v.id === "RC-6");
      record("RC-6 '--headless=new enables WebMCP with no flag' row exists, is registered, and fires", hasRow && inRegister && caught);
    } finally {
      fs.unlinkSync(abs);
    }
  }

  // 11. BW-34 (D-42/N-01, "distinguishes revoked from unknown"): a claim
  //     that the browser tells a revoked tool apart from an unregistered one
  //     must fail — both return CDP -32602 and are indistinguishable to the
  //     client (erp/FACTS.md:761).
  {
    const fixturePath = "kb/pits/__selftest-fixture-bw34.md";
    const abs = path.join(REPO_ROOT, fixturePath);
    fs.writeFileSync(abs, "The client distinguishes revoked from unknown tool names.\n");
    let vs;
    try {
      const patterns = loadPatterns();
      const hasRow = patterns.WORD.some((p) => p.id === "BW-34" && p.pattern === "distinguishes revoked from unknown");
      vs = scanFile(fixturePath, patterns);
      const caught = vs.some((v) => v.class === "BANNED WORDING" && v.id === "BW-34");
      record("BW-34 'distinguishes revoked from unknown' row exists and fires", hasRow && caught);
    } finally {
      fs.unlinkSync(abs);
    }
  }

  // 12. BW-35 (D-42/S9, "evidence of rarity"): the framing is banned, the
  //     honest numeral is not — a document citing the true 0/420 gap must
  //     still pass as long as it doesn't frame it as evidence of rarity.
  {
    const fixturePath = "kb/pits/__selftest-fixture-bw35.md";
    const abs = path.join(REPO_ROOT, fixturePath);
    const violating = "Strict per-field provenance hit 0 of 420 surveyed repos, evidence of rarity worth a badge.\n";
    const honest = "Strict per-field provenance hit 0 of 420 surveyed repos; the gap is unrewarded, not unclaimed.\n";
    fs.writeFileSync(abs, violating);
    let vsViolating, vsHonest;
    try {
      const patterns = loadPatterns();
      const hasRow = patterns.WORD.some((p) => p.id === "BW-35" && p.pattern === "evidence of rarity");
      vsViolating = scanFile(fixturePath, patterns);
      fs.writeFileSync(abs, honest);
      vsHonest = scanFile(fixturePath, patterns);
      const caughtFraming = vsViolating.some((v) => v.class === "BANNED WORDING" && v.id === "BW-35");
      const numeralClean = !vsHonest.some((v) => v.id === "BW-35");
      record("BW-35 'evidence of rarity' fires on the framing and never on the honest 0/420 numeral", hasRow && caughtFraming && numeralClean);
    } finally {
      fs.unlinkSync(abs);
    }
  }

  // 13. D-43: --check-restrictions passes against the real repo as shipped —
  //     every ruled restriction in RULED_RESTRICTIONS has its row(s) or its
  //     recorded exemption. A quiet copy of checkRestrictions() so this
  //     check doesn't also print to stdout during --selftest.
  {
    const patterns = loadPatterns();
    const have = (cls, id) => (patterns[cls] || []).some((p) => p.id === id);
    const decisionsAbs = path.join(REPO_ROOT, "erp/DECISIONS.md");
    const decisionsText = fs.existsSync(decisionsAbs) ? fs.readFileSync(decisionsAbs, "utf8") : "";
    const allCovered = RULED_RESTRICTIONS.every((entry) => {
      if (entry.type === "row") return entry.ids.every(([cls, id]) => have(cls, id));
      if (entry.type === "exempt") return entry.markers.every((m) => decisionsText.includes(m));
      return false;
    });
    record("--check-restrictions passes: every ruled phrase restriction has a row or a recorded exemption", allCovered);
  }

  // 14. D-43 regression: a ruled restriction with NEITHER a row NOR a
  //     recorded exemption must make --check-restrictions fail. Plants a
  //     fake manifest entry the current registries and DECISIONS.md cannot
  //     satisfy, proving the checker doesn't just always pass.
  {
    const patterns = loadPatterns();
    const have = (cls, id) => (patterns[cls] || []).some((p) => p.id === id);
    const fakeEntry = { name: "__selftest fake gap__", type: "row", ids: [["WORD", "BW-999-does-not-exist"]] };
    const wouldFail = !fakeEntry.ids.every(([cls, id]) => have(cls, id));
    record("--check-restrictions design can actually fail (a fabricated gap is detected, not silently passed)", wouldFail);
  }

  let allPass = true;
  for (const c of checks) {
    console.log(`${c.pass ? "PASS" : "FAIL"}  ${c.name}`);
    if (!c.pass) allPass = false;
  }
  return allPass;
}

function assertRegisterQuiet() {
  const abs = path.join(REPO_ROOT, RETRACTED_FILE);
  if (!fs.existsSync(abs)) return false;
  const text = fs.readFileSync(abs, "utf8");
  return REQUIRED_RETRACTED_STRINGS.every((s) => text.includes(s));
}

// ── --check-restrictions (D-43) ────────────────────────────────────────
//
// A hand-maintained manifest, not a prose scanner: this does not go looking
// for new ruled restrictions in erp/** (that discovery stays a manual sweep,
// same as D-41's), it proves the ones already found haven't silently lost
// their row or their recorded exemption. Each entry is either `row` (every
// listed CLASS/ID must exist in kb/webmcp/BANNED.txt) or `exempt` (every
// listed marker string must appear in erp/DECISIONS.md, read-only — this
// tool never writes there).
const RULED_RESTRICTIONS = [
  { name: "R-01/BW-01 'the tool surface is the boundary'", type: "row", ids: [["WORD", "BW-01"], ["RC", "RC-5"]] },
  { name: "erp/RISK.md §2 BW-11 'structural guarantee'", type: "row", ids: [["WORD", "BW-11"], ["RC", "RC-1"]] },
  { name: "R-20 'the five write tools'", type: "row", ids: [["RC", "RC-2"]] },
  { name: "R-21 'a specific agent'", type: "row", ids: [["RC", "RC-3"]] },
  { name: "R-13 'a commit cannot be made without a human decision'", type: "row", ids: [["RC", "RC-4"]] },
  { name: "R-30/D-45 IR-16(b) '--headless=new enables WebMCP with no flag'", type: "row", ids: [["RC", "RC-6"]] },
  {
    name: "V2/D-44 'on the spot' (verb-led family)",
    type: "row",
    ids: [["WORD", "BW-33a"], ["WORD", "BW-33b"], ["WORD", "BW-33c"], ["WORD", "BW-33d"], ["WORD", "BW-33e"]],
  },
  { name: "N-01/D-42(1) 'distinguishes revoked from unknown'", type: "row", ids: [["WORD", "BW-34"]] },
  { name: "S9/D-42(2) 'evidence of rarity' framing", type: "row", ids: [["WORD", "BW-35"]] },
  {
    name: "FACTS.md §1(a)/D-42(3) flag/empty-surface claim",
    type: "exempt",
    markers: ["D-42", "DECLARED-UNENFORCEABLE"],
  },
];

function checkRestrictions() {
  const patterns = loadPatterns();
  const have = (cls, id) => (patterns[cls] || []).some((p) => p.id === id);
  const decisionsAbs = path.join(REPO_ROOT, "erp/DECISIONS.md");
  const decisionsText = fs.existsSync(decisionsAbs) ? fs.readFileSync(decisionsAbs, "utf8") : "";

  let ok = true;
  for (const entry of RULED_RESTRICTIONS) {
    let pass;
    let detail;
    if (entry.type === "row") {
      const missing = entry.ids.filter(([cls, id]) => !have(cls, id));
      pass = missing.length === 0;
      detail = pass ? `row(s) ${entry.ids.map(([, id]) => id).join(", ")}` : `MISSING ${missing.map(([, id]) => id).join(", ")}`;
    } else if (entry.type === "exempt") {
      const missing = entry.markers.filter((m) => !decisionsText.includes(m));
      pass = missing.length === 0;
      detail = pass ? "exemption recorded in erp/DECISIONS.md" : `MISSING marker(s) ${missing.join(", ")} in erp/DECISIONS.md`;
    } else {
      pass = false;
      detail = `unknown entry type '${entry.type}'`;
    }
    console.log(`${pass ? "OK  " : "MISS"} ${entry.name} — ${detail}`);
    if (!pass) ok = false;
  }
  return ok;
}

// ── main ────────────────────────────────────────────────────────────────

function main() {
  const argv = process.argv.slice(2);

  if (argv.includes("--selftest")) {
    process.exit(selftest() ? 0 : 1);
  }

  if (argv.includes("--assert-register")) {
    process.exit(assertRegister() ? 0 : 1);
  }

  if (argv.includes("--check-restrictions")) {
    process.exit(checkRestrictions() ? 0 : 1);
  }

  const fileArgs = argv.filter((a) => !a.startsWith("--"));
  const files = fileArgs.length ? fileArgs : gitLsFiles().filter((f) => !isSweepExcluded(f));
  const violations = runScan(files);
  if (violations.length) {
    report(violations);
    process.exit(1);
  }
  process.exit(0);
}

main();
